### ISSUE TITLE
gitignore is wrong

### ISSUE THREAD

**Issue by peterennis** [kinsidar/Arrow-Of-Light#3]
The accdb and mdb files will not be committed if
gitignore is correct.
![capture217](https://user-images.githubusercontent.com/140737/32764561-0a55bf50-c8bb-11e7-96cf-2eafe0174a54.png)

**Comment by kinsidar** [comment]
Updated with this commit:

34b340c5fe5c66d1d2c0e193814086582048de79

Thanks!
